name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Windows executable
      run: flutter build windows --release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: build/windows/x64/runner/Release/
        retention-days: 30
    
    - name: Create Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/windows/x64/runner/Release/salaries_app.exe
        asset_name: salaries_app.exe
        asset_content_type: application/octet-stream 